### PR TITLE
shortening filenames of example pages

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
OK, this was much less work than the FAQs. Good to go I think.

**Comment by robertoostenveld** [comment]
are there associated test scripts that are to be renamed for consistency?

**Comment by schoffelen** [comment]
probably, yes.

**Comment by robertoostenveld** [comment]
this looks complete, so I will merge. 

that also allows @RenedBruin and me to check whether building the website still works, as Rene made some changes to the containers.

**Pull request merged**
