### PR TITLE
Time-frequency analysis with EEG data (Tutorial Oslo)

### PR DESCRIPTION
**Pull request by britta-wstnr**
Tutorial on time-frequency analysis using EEG data for the workshop in Oslo.

This is still (mildly) work in progress, left to do is: 
- [x] add relevant video tutorial
- [x] clean up and spell check

@robertoostenveld is there any checks I can do from my side to see whether it compiles fine? Renders to pdf, but figures etc. is of course missing ...

### CODE REVIEW

**Comment by britta-wstnr** [comment]
I gave it another pass, reviews now welcome @robertoostenveld !

CC @ualsbombe

**Comment by robertoostenveld** [comment]
@britta-wstnr if you want to compile it locally to html (and serve it locally), you have to install https://jekyllrb.com, which is built using Ruby. For me that was also new, but not very hard to get running. Very short some terminology: Bundler is like npm for Node.js, and a bit like pip for Python. Gems are packages.  In https://github.com/fieldtrip/website/blob/master/README.md you can see the command that I always use, which then serves the website on http://localhost:4000. There are some packages (gems) you should install along with it, probably you should be able to figure those out from the error messages. 

Since you are going to do a new install, could you please copy and paste the commands that you use? We can then add those to the README.md as technical instructions.

**Comment by robertoostenveld** [comment]
looks good to me. I have only read the text (in an editor), not rendered the html and not looked at the figures. But I propose just to merge and see how it looks on the website. Of course you can still use the previous [comment](https://github.com/fieldtrip/website/pull/145#issuecomment-498615995) to do it locally, perhaps also for other pages etc.

**Comment by britta-wstnr** [comment]
@robertoostenveld I fixed the references. I rebased after fetching upstream - but it appears as if that actually did not work? Were your commits not in this upstream repo? I am sorry, I should have checked first with you how you do things at FieldTrip before doing my "usual program".
I guess I have to ask you to push your commits again, sorry!!

I will check out Jekyll once I have the beamformer tutorial done - this was on my list anyway for a while now, so perfect reason to finally get my hands on it! I will get a step-by-step of my process.

**Comment by robertoostenveld** [comment]
rebasing is too complex for me... 

This morning I had already fixed the reference in your md file as well, plus made some other changes (tabs to spaces, changed an info into an exercise). 

Your force-push seems to have overwritten and thereby obsoleted my commit. My fault: I should have made it more clear that my review of your branch would go as a commit directly against your branch. My commit of this morning is at [ 9861af2](https://github.com/fieldtrip/website/commit/9861af2914d633e0d79c8bd47d33ddfcbdb4d9b1), please check whether there is anything useful you want to copy over. The tab-to-space formatting needs to be done anyway: I always use the https://atom.io/packages/prettier-atom plugin in Atom for that, it features a very simple cleanup of markdown.

**Comment by britta-wstnr** [comment]
Okay I will. I guess the confusion was that I thought you committed directly to my PR, so I would be able to fetch that. Then rebasing + force-push (necessary after rebase)  should have carried your changes as well ... My fault!! I will do a comparison to your commit.

Thanks for the package suggestion, I am not using Atom, but will enable the equivalent for Markdown in my editor!

**Comment by robertoostenveld** [comment]
Do you want me to merge, to see how it looks on the website?

**Comment by britta-wstnr** [comment]
I am done on this - if you want me to test it locally, I will try and install Jekyll after I am done with the beamforming tutorial. Otherwise this should be good to go!

**Comment by robertoostenveld** [comment]
let's just merge and see how it goes. I will keep an eye on the web server to check whether there are problems compiling the markdown into html.

**Pull request merged**
