### PR TITLE
Definitive program added

### PR DESCRIPTION
**Pull request by dieloz**

### CODE REVIEW

**Comment by dieloz** [comment]
the workshop page doesn't work
http://www.fieldtriptoolbox.org/workshop/madrid2019
Could it be because the accents?

**Comment by robertoostenveld** [comment]
I do not know why the page failed to build, but also on my local computer it failed. I suspect it had not to do with the special characters this time (since I recall that to give an explicit error). Possibly it had to do with mixed DOS/UNIX line endings in the text file (which are invisible).

**Comment by robertoostenveld** [comment]
I just made a new page/file, and copied the existing content back in... now it works again.

**Comment by robertoostenveld** [comment]
Looking at https://github.com/fieldtrip/website/commit/1e4b8206e5b3a7a12e9c9a399dcc421a89b26d58 it seems that a small error was made on the 1st line, which had 4x ---- whereas it should be 3x ---. The result is that jekyll does not recognize the file as a web page. Something to remember for debugging next time.

**Pull request merged**
