### PR TITLE
add news item for release 20200919

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
let's see whether the tweet works...

**Comment by robertoostenveld** [comment]
... nope, the tweet did not appear. 

But the additional debug information printed by https://github.com/fieldtrip/automation/blob/master/send-tweet-newsitem.sh shows something interesting

```
not sending tweet: FieldTrip version 20200911 was just released, now with support for SNIRF and other NIRS improvements. See http://www.fieldtriptoolbox.org/#11-September-2020
sending tweet: FieldTrip version 20200919 was just released with updates to the BIDS functions. Check the latest and greatest at http://www.fieldtriptoolbox.org/#19-september-2020
```

There are two tweets which are mixed up.

**Comment by elshafeh** [comment]
20200911 tweet was sent

**Comment by robertoostenveld** [comment]
> 20200911 tweet was sent

Yes, that was after I manually triggered it once more. I wonder whether it is due to the machine on which it executes: the automatic ones run on a compute node, whereas if I start it by hand I am using mentat001-5.

**Comment by robertoostenveld** [comment]
I will continue to investigate it...

**Comment by robertoostenveld** [comment]
I believe I have found it: the compute node running the script was using the incorrect Ruby version,  causing the "t" command (the command-line twitter interface) to fail. I have changed the path settings and just ran a successful test with an older release that had not been tweeted yet. Note that I have deleted the tweet again, as not to confuse people.

**Comment by schoffelen** [comment]
did you also added some hidden gems?

**Pull request merged**
