### PR TITLE
we made some changes

### PR DESCRIPTION
**Pull request by zpopov**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
great that you are managing with git!

let me know when it is ready to merge.

**Comment by zpopov** [comment]
well right now JM is in his second 40 minute zoom session with Tzvetan, and controlling the keyboard

**Comment by zpopov** [comment]
This change can be merged now, please.

**Comment by robertoostenveld** [comment]
can @schoffelen do that? Perhaps he can share his screen so that you also see what happens on "our" side

**Comment by robertoostenveld** [comment]
Please note that I just made a small fix.  If you want to do further edits to `sofia2024.md`, please to a git pull prior to making those changes.

**Pull request merged**
