### PR TITLE
add news item for release 20210603

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
this release contains improved handling of NaNs in timelockanalaysis and timelockgrandaverage. It is a relevant step in better supporting bad channel-segments, therefore strategically relevant, but only one step - more is needed and is planned for the coming months. Should we announce this release now?

**Comment by robertoostenveld** [comment]
we could also wait and bundle a few releases in a single announcement, e.g. next week or so

**Comment by schoffelen** [comment]
It's a fair consideration to bundle it. On the other hand, we could also announce it now, and perhaps add e few words about incremental (but unmentioned) improvements over the past. For instance, a while ago I have swept the preproc functions to ensure nan-awareness wherever possible. I think I also wrote a test function for that. I can look that one up if you want.

**Comment by elshafeh** [comment]
I vote for bundling

**Comment by robertoostenveld** [comment]
a revamped rejectvisual with support for bad channel-segments (now only channels, or segments) would be a potential killer application. The incremental work towards improving the nan handling (in preproc and grandavg) is currently not so accessible yet to the users. I also think that we should bundle, and try to prioritize the rejectvisual improvement.

**Pull request closed without merging**
