### PR TITLE
added MPVA-Light tutorial 

### PR DESCRIPTION
**Pull request by treder**

### CODE REVIEW

**Comment by treder** [comment]
OK done from my side

**Comment by schoffelen** [comment]
OK thanks. I'll merge, play it, and if OK link it to the outside world. OK?

**Comment by treder** [comment]
Fantastic thanks! Hopefully ppl will find it useful.

**Comment by schoffelen** [comment]
No doubt this will be used Matthias. Looking over the tutorial (with figures now, it has rendered nicely!) I wonder whether you would be fine if I change a bit the option handling in ft_statistics_mvpa.
Specifically, I'd like to move the mv_* specific options to a cfg.mvpa field. Admittedly, this is arguable, but these days we tend to more and more use this style.

For instance in ft_sourceanalysis we have a cfg.method, and then use cfg.(cfg.method).someoptions, to keep the number of options at the main level of the cfg somewhat limited. If that's fine with  you, I will change this.

**Comment by schoffelen** [comment]
Also, with the spatial searchlight in the tutorial you now use a distance matrix based heuristic, based on the 2D projected sensors. We could consider making it consistent with the cfg.neighbours (and also call the option like that) field in ft_megplanar or ft_statistics_montecarlo

**Comment by treder** [comment]
Happy if you want to change the mvpa field, it's good to keep things separated. This way I can also develop the toolbox without worrying that something in Fieldtrip breaks.

**Comment by schoffelen** [comment]
that was my thinking exactly.

**Comment by treder** [comment]
Re:neighbourhood structure, I agree. MVPA-Light also allows for a binary adjacency matrix so perhaps the easiest thing would be to translate the neighbours cell array into an adjacency matrix in ft_statistics_mvpa, or what do you think? I can probably look into that in the next days and do another pull request.

**Comment by schoffelen** [comment]
You may want to cross-check this with some code in ft_statistics_montecarlo.

In general, fieldtrip supports cfg.connectivity for the neighbourhood, as a generic representation of spatial neighbours, in ft_statistics_montecarlo there's some code that transforms cfg.neighbours into such a matrix. 

So no need to reinvent the wheel.

**Pull request merged**
