### PR TITLE
Create using_the_threshold_free_cluster_enhancement_method_in_cluster…

### PR DESCRIPTION
**Pull request by yingjoeyzhou**
outline of the contents => will fill in the details asap when others agree with the proposed outline.

### CODE REVIEW

**Comment by schoffelen** [comment]
This relates also to #375

**Comment by robertoostenveld** [comment]
@yingjoeyzhou do you want to document this in the form of a FAQ (i.e. mainly text), or rather in the form of an example MATLAB script (i.e. mainly code, with some text) that is based on some example data?

**Comment by yingjoeyzhou** [comment]
But intuitively ppl won't expect to see an explanation on TFCE in an
"example script" page, right?

**Comment by robertoostenveld** [comment]
I don't know. I was just asking you what you have in mind. With the "How to use the method in fieldtrip?" you suggest that you want to give example code, rather than the minimal textual description "You can use it by specifying cfg.correctm=`tfce`". 

If the code is more than a few lines, an example script (with some example data) might be a better format than a short FAQ. It is also uncommon (but not impossible) for a FAQ to have sub-sections with separate questions. There are some FAQs that do it, but FAQs tend to be short, examples tend to be longer, and tutorials are the longest.

**Comment by robertoostenveld** [comment]
I suggest you just add the content first, we can change the place where it appears on the website later.

**Comment by yingjoeyzhou** [comment]
I'm afraid I noticed an issue #1731 that we need to fix..

**Comment by robertoostenveld** [comment]
Hi @yingjoeyzhou https://github.com/fieldtrip/fieldtrip/issues/1731 has been fixed for some while. Are you still planning to write this FAQ? If not, I suggest you close this PR.

**Comment by yingjoeyzhou** [comment]
Hi Robert, Thanks for the reminder. I thought I sent the pull request? I'm
working towards a deadline atm but i'll dig it out Wed or Thu. Should be
straightforward to share it. Apologies for the inconvenience.

**Comment by robertoostenveld** [comment]
There is a pull request, but it only contains an outline. I look forward to reading what you wrote.

**Comment by robertoostenveld** [comment]
this has been implemented with #420

**Pull request closed without merging**
