### PR TITLE
add news item for release 20220310

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by elshafeh** [comment]
nothing news worthy right?

**Comment by robertoostenveld** [comment]
Well, I think that the change to sourceplot might be worth mentioning. It now turns the MRI such that [Mr Potatohead](https://www.fieldtriptoolbox.org/faq/my_mri_is_upside_down_is_this_a_problem/) situations should be avoided. I have not experienced it myself yet, but perhaps @schoffelen can make an assessment whether it is worthy of a tweet/newsitem.

**Comment by schoffelen** [comment]
@elshafeh: Hi Alma, would you be able to tweetify my suggested changes to the news item?

**Comment by robertoostenveld** [comment]
I moved the (more important) sourceplot improvements in front of edf2fieldtrip. I also extended the tweet a bit, but that might still be further improved.

**Pull request merged**
