### PR TITLE
add news item for release 20201103

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I propose to also remove the list with commits, the link to github shows that as well

**Comment by schoffelen** [comment]
Sure, do you also want a little bit more detail on the artifact representation? 
E.g. highlight the per-channel-segment representation and the optional tabular format?

**Comment by robertoostenveld** [comment]
Yes, I think that would be worthwhile to mention. The (now fixed) bugs in the code not, though

**Comment by robertoostenveld** [comment]
I changed the `from ... to` comparison that points to github. The last  release announced on twitter and mentioned on the website was 20201009, so I think it is fair to show all changes relative to that version. 

@schoffelen can you do a final check and then merge?

**Comment by schoffelen** [comment]
ZEGU (=dutch for LGTM)

**Pull request merged**
