### PR TITLE
display list of latest commits on homepage

### LINKED ISSUE #8: Display latest commits on FT website homepage

### PR DESCRIPTION
**Pull request by Spaak**
Resolves #8, see also https://github.com/fieldtrip/automation/pull/7 and https://github.com/fieldtrip/automation/pull/9

### CODE REVIEW

**Comment by robertoostenveld** [comment]
This works for me. It is a clean and concise change to the website code. For reference, this is how it looks like (running a local copy of the website myself).

Screenshot 2020-08-28 at 13 32 31

@schoffelen what do you think of it?

**Comment by schoffelen** [comment]
I think that indeed it would be good to give the users a feel about what's going on in terms of code development. As per the screenshot that Robert pasted in above, I think that quite a large amount of screen real estate is absorbed by relatively low amount of data. 
What about organizing the reports of the code changes per new release version? I.e. create an automated news item once a new release is created, which can look something like Robert's Feb 19 comment in https://github.com/fieldtrip/automation/pull/7

**Comment by robertoostenveld** [comment]
This will be solved using #275 rather than with a javascript plugin.

**Comment by Spaak** [comment]
@schoffelen closing #8 reminded me about this. In the end we decided not to tweet/post news items about every commit (a good thing). Given that strategy, we could, I think, still consider displaying the commits on the homepage, as per this PR. Such a list of commits does not "pollute" the news or twitter feeds, and would still give the feeling of activity to the homepage "for free".

What do you two think? (I'll have to file this PR anew, as I've changed the name of my repository.)

**Comment by schoffelen** [comment]
Ah, I thought that we decided against posting on the home page, because it is a bit off-balance with respect to the amount of information conveyed, and the amount of screen real estate needed

**Comment by Spaak** [comment]
Yes you're right it is a relatively large amount of screen real estate. I don't have a strong preference here, actually; I commented here only because this:

> This will be solved using #275 rather than with a javascript plugin.

in the end solves something a bit different.

**Pull request closed without merging**
