### PR TITLE
Contribution to the FAQ site about 'should I rereference prior to or …

### PR DESCRIPTION
**Pull request by felix-bott**
…after ica for artifact removal' including images.

As discussed on Slack. I could also provide some figures as mentioned in the last two paragraphs. Best, Felix

### CODE REVIEW

**Comment by schoffelen** [comment]
It would be great if you could also add the figures! Do you know how that works?

**Comment by felix-bott** [comment]
Hi Jan-Mathijs,

not sure how the figures can be added. I guess it is explained in one of the READMEs?

Best,

Felix

On 17. May 2021, at 08:42, Jan-Mathijs Schoffelen ***@***.******@***.***>> wrote:



It would be great if you could also add the figures! Do you know how that works?

**Comment by schoffelen** [comment]
Awesome! I was just working on the documentation to describe the addition of figures. This is exactly how it should be done. The only thing I'd prefer, is to add the figures in bitmap format (*.png or *.jpg) to avoid surprises when rendering the figures.

We'll only find out how it looks, once the PR is merged and the website is built. There are tricks of locally compiling (and thus checking the rendering), but this is a bit of a hassle. It requires the installation of ruby and jekyll, as explained in the readme.md of the website repo

**Comment by felix-bott** [comment]
Ok, no problem. I'll change the format then. Thanks!

**Comment by schoffelen** [comment]
Shall I merge, and see how it renders, or should we also already add a link to this new faq on faq.md?

**Comment by felix-bott** [comment]
Let's see how it renders first. What do you think with regards to the content?

**Comment by schoffelen** [comment]
I think that it's a nice FAQ. Essentially, your point is that if you add the implicit reference (i.e. the channel that was the reference, which is not usually included in the datafile), actually the order of steps does not matter. So, if we would generalise, the referencing scheme can be whatever (e.g. a linked mastoid or a Laplacian). Would it be needed you think to add a cautionary statement about removing bad channels first, prior to attempt any IC decomposition or avg-reref? (although perhaps it's outside the scope of this faq)

**Comment by felix-bott** [comment]
Good, thanks. Your suggestion concerning the cautionary statement makes sense to me although I really lack the experience to have a strong opinion on that. Feel free to edit in whichever way you deem necessary.

**Comment by felix-bott** [comment]
The rendered page looks ok to me. Do you want to add the link in FAQ.md or shall I?

**Comment by felix-bott** [comment]
Yes, I can send you the code. How should I do this -via email?

**Comment by schoffelen** [comment]
I was more thinking of adding the code to the faq as well. I.e. starting off from a data structure obtained after ft_preprocessing, and then having 2 recipes: 
- add implicit reference (I think that this can be done with ft_preprocessing), followed by ica
- average reference, followed by ica

**Comment by felix-bott** [comment]
Hi! I added the code now in a straightforward way. Where can I upload the example dataset?

**Comment by robertoostenveld** [comment]
if you use any of these https://www.fieldtriptoolbox.org/faq/how_should_i_send_example_data_to_the_developers/ and send @schoffelen or me a direct message with the download link, we will copy it to ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/example/

**Comment by felix-bott** [comment]
ok, here is the wetransfer link which I also sent to Jan-Mathijs via email: https://we.tl/t-0pleNwG0EW

**Comment by robertoostenveld** [comment]
I have copied it, it is now available under ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/example/rereference/

**Comment by felix-bott** [comment]
The link to the example data has now been added to the faq page.

**Pull request merged**
