### PR TITLE
shorten filenames of page

### PR DESCRIPTION
**Pull request by schoffelen**
to facilitate reorganization of the website.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
a lot of files were changed. How far (in percentage or so) do you think you got?

**Comment by robertoostenveld** [comment]
The FAQ directory looks now clean and complete, right? Shall I review, test and merge?

**Comment by schoffelen** [comment]
I think that this one indeed is ready for review: I did a full sweep of the FAQ folder + the assets/faq

Next in line is the example scripts, I haven't touched those, yet

**Comment by robertoostenveld** [comment]
I will pull this branch and deploy locally to see whether there are any issues. If not, I'll merge.

**Comment by schoffelen** [comment]
I rendered the page locally and fixed some broken links.

I tried the ```wget -spider``` but did not manage to extract good intel from that. Hence I followed all the links on the faq landing page, and all seems in order after my latest commit. I haven't checked the pages with images (since I renamed the folders)

**Comment by robertoostenveld** [comment]
Let me give it a try as well.

**Comment by robertoostenveld** [comment]
I noticed that there are non-functional redirections, for example http://127.0.0.1:4000/faq/how_can_i_import_my_own_dataformat works on `master`, but not on  `fname_short`. It should redirect to http://127.0.0.1:4000/faq/dataformat_own/ and the redirect is also in the md file... weird.

**Comment by robertoostenveld** [comment]
Ah, found it: the `redirect-from:` in the header should be `redirect_from:` with an underscore. I will change it.

**Comment by robertoostenveld** [comment]
Ok, I believe all links are working again. Note that quite a few of the broken links were not due to the faq renaming, but due to previous refactoring of figures and workshop pages, but these had not been detected yet.

**Pull request merged**
