### PR TITLE
Collapsing text on recent news items

### PR DESCRIPTION
**Pull request by elshafeh**
Something I noticed on the website now is that some of the news items are quite long. Especially this 24th June 2020 one. I think aesthetically it is not pleasing and could make room for other news items. What do you think?

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Does this work? Did you try it with a local installation of Ruby and Jekyll?

**Comment by robertoostenveld** [comment]
oh, this is not jekyll specific but using https://www.w3schools.com/tags/tag_details.asp and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details. I was not aware of this, cool!

I will try it out

**Comment by robertoostenveld** [comment]
the collapsing works, but the content in the collapsed section is not translated from Jekyll/Markdown to html, which means that it is raw (no hyperlinks, \*\* instead of bold, etc.) 

If you want to come with an alternative, please go ahead. Otherwise, I suggest not to spend too much time on this.

**Comment by elshafeh** [comment]
Soo the only I got his to work was through editing the _config.yml and GemFile (https://github.com/github/jekyll-commonmark-ghpages#installation)

**Comment by elshafeh** [comment]
closing this one..

**Pull request closed without merging**
