### PR TITLE
Wittonc patch 1

### PR DESCRIPTION
**Pull request by wittonc**
Updated the epilepsy tutorial with clinical information, use of AnyWave to screen data, analysis of the Elekta dataset.
Still to add: images

### CODE REVIEW

**Comment by schoffelen** [comment]
Top. Have the figures changed? If so, could you add new versions of them as well

**Comment by wittonc** [comment]
There should be some additional figures showing the downstream output for the CTF file and for the Elekta data.  I want to be sure that we are using the best pair of datasets before I add them though. Sorry this means you can't see the output right now.

**Comment by schoffelen** [comment]
OK

**Comment by schoffelen** [comment]
And apologies: I didn't read your comment in sufficient detail...

**Pull request merged**
