### PR TITLE
FIX: typos in kit/yokogawa/ricoh documentation

### PR DESCRIPTION
**Pull request by sappelhoff**
when trying to solve https://github.com/bids-standard/bids-specification/pull/653, I stumbled over a few typos here that I want to fix with this PR.

### CODE REVIEW

**Comment by sappelhoff** [comment]
furthermore, the link to yokogawa is broken on this part of the website: https://www.fieldtriptoolbox.org/external_links/

image

**Comment by schoffelen** [comment]
Thanks! 

Regarding the broken link, perhaps we could replace it to point to https://www.ricoh-usa.com

**Comment by schoffelen** [comment]
It turns out that most of the links are broken ,by the way.

The BTi/4D points to CTF :)

**Comment by sappelhoff** [comment]
uff, so that'd need a much more thorough rework.

Just for this particular PR: I just checked https://www.ricoh-usa.com/ and it seems a bit too general to be useful IMHO.

**Comment by schoffelen** [comment]
I agree. But they have a link in there that points to something that looks like an MEG machine, rather than a printer, so I plugged in that link for the time being.

**Comment by sappelhoff** [comment]
Fair enough --> and for sure better than a 404 link. Thanks!

**Pull request merged**
