### PR TITLE
draft: cluster tutorial resting state added

### PR DESCRIPTION
**Pull request by dieloz**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I presume this PR is to remain open for a bit longer, until it gets more final. Right?

**Comment by robertoostenveld** [comment]
@aranas this is also relevant for you

**Comment by dieloz** [comment]
Sure: I'll upload the figures tonight. I wanted to upload the example script to show you what I did and see what I'm doing wrong

**Comment by aranas** [comment]
Hi @dieloz concerning the markdown syntax such as warning boxes etc, even when they don't show up in the Github view, I suspect them to render once it is converted to the actual website. I.e. if you look at the Github code for some older tutorials they also have the raw syntax for boxes, but it does show up correctly on the website. Seems to me like part of the magic happens when md is converted to html or so. For the code it seems like the tab is enough as a marker.

**Comment by dieloz** [comment]
Thanks for your input @aranas !

**Comment by robertoostenveld** [comment]
"part of the magic happens when md is converted to html" -> yes, that is how it works. It uses https://jekyllrb.com for that. 

Using the "markdown preview" plugin Atom can also give a preview, and github itself also gives a preview, but neither does the formatting precisely the way that it it is done by jekyll.

I have jekyll installed on my laptop and can see the final version prior to doing a commit or when reviewing a PR for merging. It is not easy to install, so don't recommend  this for you. If you get it more or less right in a markdown previewer (like Atom), it is good enough.

**Comment by robertoostenveld** [comment]
Since there are 4 hands-on sessions, we need 4 pages on the website. I have made placeholders for them:

```
workshop/madrid2019.md
workshop/madrid2019/tutorial_cleaning.md (from Sophie)
workshop/madrid2019/tutorial_erp.md
workshop/madrid2019/tutorial_freq.md
workshop/madrid2019/tutorial_stats.md
```

Rather than putting them under the examples section, it is better to keep them all close-by for now. Also, the images should go under /assets/img/workshop/madrid2019.

**Comment by robertoostenveld** [comment]
@dieloz you will see that I just pushed some changes to your madrid19 branch. I can do that because you submitted it as a PR, which gives me permission to update it.

Please pull my changes to your madrid19 branch prior to making other changes, otherwise you might get conflicts.

**Pull request merged**
