### PR TITLE
create content for FEMfuns workshop 2022

### PR DESCRIPTION
**Pull request by mcpiastra**

### CODE REVIEW

**Comment by mcpiastra** [comment]
dear all, we are planning a workshop on FEMfuns in FieldTrip at the Donders based on the work done here: https://www.fieldtriptoolbox.org/development/project/femfuns/
best,
Maria Carla

**Comment by robertoostenveld** [comment]
Looks good. Is it ready to be merged?

**Comment by robertoostenveld** [comment]
oh, perhaps you can add a tweet to it, so that it reaches a much wider audience. See https://raw.githubusercontent.com/fieldtrip/website/master/_posts/2022-10-07-multi.md for an example. The idea is that you just add the `tweet:` to the header, and it will appear on https://twitter.com/fieldtriptoolbx

**Comment by robertoostenveld** [comment]
When tweeting, it is smart to tag people by their twitter handle with the `@`. No idea whether Thom, Geertjan and/or you are on twitter.

**Comment by mcpiastra** [comment]
thanks. the link to the femfuns2022.md is missing, right? I saw links to folders but not to md files..should I create an empty folder with the same name?

**Comment by robertoostenveld** [comment]
No need to make a folder, as there is only a single file. The link should look like this

`[FEMfuns workshop](/workshop/femfuns)`

**Comment by mcpiastra** [comment]
femfuns or femfuns2022? I tried both and the link does not work...but it might be because the file is not there yet..?
the md filename is femfuns2022

**Pull request merged**
