### PR TITLE
Update symmetry tutorial with simulations

### PR DESCRIPTION
**Pull request by henneysq**
This pull request adds details to the tutorial on beamformer source estimation with symmetry constraints to show the effects of this on correlated sources.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Instructions for running the website locally are documented here https://github.com/fieldtrip/website/blob/master/README.md#evaluating-the-website-locally

I hope you can get that to work. I use [rvm](https://rvm.io) to bootstrap the Jekyll stack.

**Comment by henneysq** [comment]
@robertoostenveld do you want me to add some details to the real-data example based on Popov2018?

**Comment by henneysq** [comment]
STATUS:
The symmetry simulations tutorial now renders in its entirety and contains four examples. I can merge all the code into two for loops instead to make it less comprehensive, but I think this sequential structure is easier to follow as a tutorial.

I will add some descriptions to the plots, and feel free to do the same if you want to attach any comments.

**Comment by robertoostenveld** [comment]
Hi Mark, pointing to Popov2018 would be useful. If you feel it looks more or less OK, I suggest to merge, then check out how it looks online (which I will do as well)  and then make further small changes.

**Comment by henneysq** [comment]
> Hi Mark, pointing to Popov2018 would be useful. If you feel it looks more or less OK, I suggest to merge, then check out how it looks online (which I will do as well) and then make further small changes.

Okay. I will break down and describe the ASSR_lcmv.m script from Popov2018, then mark the PR ready to merge.

**Comment by henneysq** [comment]
I took the `ASSR_dics.m` from Popov2018 apart and described the content for a single subject.

**Comment by robertoostenveld** [comment]
let me merge, and let's then have a look at it online.

**Pull request merged**
