### PR TITLE
ENH: added spectral features extraction demo to irasa doc

### PR DESCRIPTION
**Pull request by StolkArjen**
This PR demonstrates the use of IRASA for extracting spectral features from human ECoG data. The PR includes surface plots of sensorimotor alpha and beta rhythms, as well as overall streamlining of the example document.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Hi Arjen, can you update your version with the recent changes from Rui and resolve the merge conflicts in the commit?

**Comment by StolkArjen** [comment]
Ah, shoot. Rui just mentioned she'd close hers first until after this one
haha.

**Comment by ruiliu-psy** [comment]
Hoi Robert, thanks for pulling in my earlier PR. Also, thank Arjen for adding the example of ECoG. It looks great, except for several minor wording that I'll submit a commit later, so that you guys can see if you like it not. 
Before that we'd better decide the framework of the webpage, Arjen might feel like to compress the update section of the webpage. I just explained to him the idea was that we should make the usage of the new implementation explicit to users and they suppose to get an error report linking them to the webpage telling how to adapt their pipelines and why they should. The link to the PR of the new implementation might be insufficient, as it doesn't contain the usage. He's working on it.

**Comment by StolkArjen** [comment]
Closed this PR, which is superseded by #346.

I've reinstated the "Updates" section in its original condition, and will leave it up to you guys what you want to do with it. It seems some of the details currently mentioned are more relevant to developers than to users wanting to try out the IRASA procedure, cf. visiting a wikipedia page where half of the page describes the page's history than its topic. Also, this type of information gets outdated at some point in time. Perhaps part of the Updates-related content can be moved to the respective PR on github.

**Pull request closed without merging**
