### PR TITLE
tutorial_freq added and enhancing tutorial_stats

### PR DESCRIPTION
**Pull request by dieloz**

### CODE REVIEW

**Comment by aranas** [comment]
@dieloz I will make some changes to the headers to get the correct TOC to display at the side. Also if you don't mind I would move the dataset descriptions to the dataset pages and in the tutorial only link to at, as we will be using them in multiple tutorials

**Comment by aranas** [comment]
@dieloz I looked through the tutorial_stas but the headings structure is not clear to me. After the Background heading, there is a "1. Compute within-subject structure". but I don't see a "2. Compute between-subject structure". Instead there is a "Contrast 1... "and "Contrast 2..."

Could you specify what you had in mind? Or Change it yourself directly. However, if you change the file keep in mind, that I have also made changes by now, so first pull my changes and only then push new ones please otherwise we will get lost in git chaos :)
Also, keep in mind that one hash (#) headings will not show up in the TOC

I will add missing figures and try to update the datasets on the ftp server now, will be back on this pull request in a couple hours

**Comment by dieloz** [comment]
Thanks Sophie. I fixed the heading mess but I'll wait your pull. I also created the website\assets\img\workshop\madrid2019\datasets to upload corresponding figures

Let me know when you update datasets to the FTP

**Comment by aranas** [comment]
Where did you fix the headings in this local branch of yours? Maybe you can do the following:
git pull 
git commit yourchanges
%here you might get conflicts which need resolving
git push

**Comment by dieloz** [comment]
I commited already and now I'm behind. At this point, given my github abilities, please make a pull request and when accepted by @robertoostenveld I'll commit mines

**Comment by aranas** [comment]
@dieloz I already commited to this same pull request, so my changes are in. can you put your tutorial_stats.md file in the dropbox folder? I think it might be fastest if I just take the headings from there, copy paste them into this pull request.

**Comment by aranas** [comment]
also, I can accept this pull request so Robert does not need to, as he is busy today.

**Comment by dieloz** [comment]
I just updated it in dropbox

**Comment by aranas** [comment]
perfect thx, will take care of it now and then we'll merge everything together!

**Comment by aranas** [comment]
I have confirmed the merge, the website should be up in a minute. Let's have a look at the outcome and make a new pull request if adjustments need to be made

**Pull request merged**
