### PR TITLE
Paula asked me to put the sepneca society as local organizer

### PR DESCRIPTION
**Pull request by dieloz**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
somehow the special characters in "Española" and "Psicofisiología" cause problems with converting the markdown into html (invalid byte sequence in UTF-8). I have inserted them once more.

**Comment by dieloz** [comment]
Now it worked! But next time I'll avoid accents and strange characters

**Comment by robertoostenveld** [comment]
I don’t know why yours failed. I just copied and pasted them from the guithub website back into the MD file, and then it worked. But indeed better avoid when possible.

**Comment by dieloz** [comment]
weird indeed

**Pull request merged**
