### PR TITLE
added credits and news item

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
so you apparently did not like my use of the emoji 😉

thanks for the review!

**Comment by robertoostenveld** [comment]
for reference, this related to the #368 sample size example page

**Comment by elshafeh** [comment]
haha different tastes :) 
Just to be sure, was this supposed to send out a tweet now? Cause I don't see anything ..

**Comment by robertoostenveld** [comment]
yes, there should have been an instantaneous tweet. I will check where it got stuck in the backend... Otherwise I'll send it by hand

**Pull request merged**
