### PR TITLE
updated MVPA-Light tutorial 

### PR DESCRIPTION
**Pull request by treder**
This update goes along with the update of mv_statistics_mvpa. 

Main changes: the cfg parameters have been adjusted according to the new interface. Additionally, new sections on time-frequency classification, hyperparameters, and preprocessing have been added.

### CODE REVIEW

**Review by schoffelen — CHANGES_REQUESTED** [review]
Great, ready to merge it seems, apart from the figures not having been updated. I would assume that new figures are in order, to be put in assets/img/tutorial/mvpa-light

**Comment by treder** [comment]
I see - I didn't update the figures since they basically look the same up to little cosmetic changes in the toolbox. Can you this though.

I didn't add new figures but perhaps it's useful to add them whenever there's a call to `mv_plot_result` in the tutorial. I'll do this now.

**Comment by treder** [comment]
🚀

**Comment by schoffelen** [comment]
Thanks!

**Comment by treder** [comment]
Just had a look on the FT website, looks good 👍  let's hope the FieldTrippers appreciate it too!

**Pull request merged**
