### PR TITLE
add news item for release 20230926

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by schoffelen** [comment]
Hi @robertoostenveld I noticed that it's been a while (latest one dates from january 2023) that the latest release version has been advertised on fieldtriptoolbox.org. 
This is probably because the last PRs have been closed without merging, thus not triggering the usual post commit hook voodoo that converts the associated markdown file into a post. Should we perhaps open a few of the closed PR's to catch up with a historical trace of the releases on the website.
Or perhaps restart the tradition by merging the current PR?

**Comment by schoffelen** [comment]
OK, I gave it a shot, added the external contributors for credits and made an executive summary for the most important improvements since january. Do you want to give it a read before I merge @robertoostenveld ?

**Comment by robertoostenveld** [comment]
thanks, I will have a look.

**Comment by robertoostenveld** [comment]
@schoffelen how is this? If you are fine with it, please merge.

**Pull request merged**
