### PR TITLE
Tutorial eeg

### PR DESCRIPTION
**Pull request by schoffelen**

### CODE REVIEW

**Comment by schoffelen** [comment]
this fixes most of the broken links to the figures

**Comment by robertoostenveld** [comment]
I see in the ToC structure on the right of http://www.fieldtriptoolbox.org/tutorial/networkanalysis_eeg/ that the levels of the headings are not consistent: now almost all steps fall under preprocessing

**Comment by schoffelen** [comment]
Indeed. I will quickly fix this, and try to also get the path to the missing figure 9 right.

**Comment by schoffelen** [comment]
@zpopov it seems that figure 9 is missing from the code base. can you upload please? ( I guess that this requires a new PR from your side (alternatively, just send the figure to me by e-mail, but that would be the easy way out) )

**Pull request merged**
