### PR TITLE
Syntax highlighter

### PR DESCRIPTION
**Pull request by Spaak**
Enabling syntax highlighting for code blocks.

See https://jwarby.github.io/jekyll-pygments-themes/languages/javascript.html and https://github.com/richleland/pygments-css for some possible style sheets.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Sorry for it taking some time for me to get back to this. I have pulled a local copy of your branch and checked it out locally. 

I see in the html code on localhost:4000 that it contains

    <div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>
    MATLAB code goes here
    </code></pre></div></div> 

but it is not rendered any differently than in the past. I also see in my web inspector that the highlight-friendly class is loaded. Changing e.g. the background colors of the highlight class does not make a difference. See attached screenshot.

screen shot 2019-01-14 at 11 36 44

**Comment by Spaak** [comment]
Hmm that is strange, because I get clear syntax highlighting. The following Matlab code (which I inserted into `index.md`):
```
    if true
      cfg = [];
    end
```
results in the following HTML:
```
<div class="language-matlab highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">if</span> <span class="nb">true</span>
--
  | <span class="n">cfg</span> <span class="o">=</span> <span class="p">[];</span>
  | <span class="k">end</span>
  | </code></pre></div></div>
```
Note the various `<span>`s indicating the semantic classes of the different symbols.

**Comment by robertoostenveld** [comment]
I don't get more than
```
<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>if true
  cfg = [];
end
</code></pre></div></div>
```

But good to have a handle on the problem. I suspect we have different versions of the gems. 

after cleaning and updating (on my laptop) with

    bundle pristine
    bundle update

I can see the actual versions when I do

    bundle install

which shows

```
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Using public_suffix 3.0.3
Using addressable 2.5.2
Using bundler 1.17.2
Using colorator 1.1.0
Using concurrent-ruby 1.1.4
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.10.0
Using forwardable-extended 2.6.0
Using i18n 0.9.5
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using sass-listen 4.0.0
Using sass 3.7.3
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.1.2
Using kramdown 1.17.0
Using liquid 4.0.1
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.3.0
Using safe_yaml 1.0.4
Using jekyll 3.8.5
Using posix-spawn 0.3.13
Using jekyll-last-modified-at 1.0.1
Using jekyll-sitemap 1.2.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.1
Using jekyll-toc 0.9.1
Bundle complete! 5 Gemfile dependencies, 32 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
 ```

could you compare those to yours.

**Comment by Spaak** [comment]
And it works! See e.g. http://www.fieldtriptoolbox.org/tutorial/timefrequencyanalysis/ .

**Comment by robertoostenveld** [comment]
Mooi!

**Comment by dieloz** [comment]
gorgeous work Eelke! You're the Gandalf of the syntax highlight

**Pull request merged**
