### PR TITLE
ENH - news item for critical fix

### PR DESCRIPTION
**Pull request by schoffelen**
this relates to https://github.com/fieldtrip/fieldtrip/pull/1599

### CODE REVIEW

**Comment by schoffelen** [comment]
@robertoostenveld could you have a quick read please? I have filed a PR to fix the issue in the code, and I guess that this news item can be deployed once the new fieldtrip release is in place (for now I have assumed that this will take place tomorrow -> if this indeed happens the date does not have to be adjusted here anymore).
Once the news item is deployed, I will also copy-and-paste this in an e-mail to the discussion list.

**Comment by schoffelen** [comment]
https://github.com/fieldtrip/fieldtrip/pull/1599

**Comment by robertoostenveld** [comment]
we should try to identify which systems by default would or would not be affected. E.g. CTF275 not, but neuromag systems (other than Dusseldorf)?

**Comment by schoffelen** [comment]
raw.fif on    '/home/common/matlab/fieldtrip/data/test/original/meg/neuromag306' does NOT have the channels in alphabetical order (i.e. if I do ft_read_sens('raw.fif','senstype','meg')

**Comment by robertoostenveld** [comment]
all of these neuromag datasets are not in alphabetic order

```
basedir = '/home/common/matlab/fieldtrip/data/test';

neuromag = {
  './bug1792/20130418_test_cHPI.fif'
  './bug1792/matteo_cHPI.fif'
  './bug1792/sample_chpi.fif'
  './bug1792/sample_chpi_short.fif'
  %  './bug1808/reduced.fif' % this is alphabetic
  %  './bug1914/conversion_testing_MEGEEG_raw.fif'
  %  './bug1914/conversion_testing_MEGandperipheral_raw.fif'
  %  './bug1914/conversion_testing_OnlyMEG_no_triggers_raw.fif'
  %  './bug1914/conversion_testing_OnlyMEG_with_triggers_raw.fif'
  './bug1971/test-ave.fif'
  './bug1971/test_raw.fif'
  './bug2036/sample_audvis_raw.fif'
  './bug2170/an05a4_ss.fif'
  './bug2767/01_ljh_firststd_meg_182.fif'
  './bug731/test_bug731.fif'
  %  './original/meg/neuromag122/jg_single_01raw.fif' % this is alphabetic
  './original/meg/neuromag306/raw.fif'
  './original/meg/neuromag306/run_01_raw.fif'
  './original/rikhenson/Sub15/MEEG/run_01_raw.fif'
  './original/rikhenson/Sub15/MEEG/run_01_sss.fif'
  %  './bug3375/elekta/jn_multimodal_chpi_raw_sss.fif' % this is alphabetic
  };



for i=1:length(neuromag)
  dataset = dccnpath(fullfile(basedir, neuromag{i}));
  hdr = ft_read_header(dataset, 'checkmaxfilter', false);
  grad = ft_read_sens(dataset, 'senstype', 'meg');
  
  meglabel_hdr = ft_channelselection('MEG', hdr.label);
  meglabel_grad = ft_channelselection('MEG', grad.label);
  
  assert(~isequal(hdr.label, sort(hdr.label)));   % not in alphabetical order
  assert(~isequal(grad.label, sort(grad.label))); % not in alphabetical order
  
  [sel1, sel2] = match_str(hdr.label, meglabel_hdr);
  assert(all(diff(sel1)>0)); % monotonously increasing
  assert(all(diff(sel2)>0)); % monotonously increasing
  
  [sel1, sel2] = match_str(meglabel_hdr, meglabel_grad);
  assert(all(diff(sel1)>0)); % monotonously increasing
  assert(all(diff(sel2)>0)); % monotonously increasing
  
end
```

**Comment by robertoostenveld** [comment]
These CTF datasets do have the channels in alphabetical order

```
ctf = {
  './original/meg/ctf151/Subject01.ds'
  './original/meg/ctf275/A0132_Aud-Obj-Recognition_20051115_02.ds'
  './original/meg/ctf275/TacStimRegressConfound.ds'
%  './original/meg/ctf64/Wat123r1raw.ds' % cannot be read with default implementation 
  './bug3280/A1826_comparisonSEF_20161212_02.ds'
  './bug3297/testMEG001_1200hz_20170517_05.ds'
  './bug3375/ctf/muenster_A1331.ds'
  './data2bids/mous/sub-A2002/meg/sub-A2002_task-auditory_meg.ds'
  './data2bids/mous/sub-A2002/meg/sub-A2002_task-rest_meg.ds'
  };
```

**Comment by schoffelen** [comment]
@robertoostenveld : would it be an idea to copy over those snippets of test code to the issue on the code repo? This one will be linked in the tweet and news item.

**Comment by robertoostenveld** [comment]
for reference and to follow up on our zoom chat this morning (about also documenting the channel order): in prepare_freq_matrices the channel order is according to the input cfg

https://github.com/fieldtrip/fieldtrip/blob/2a67cb59746eb81fe05bc118c96d5f257a63f51c/private/prepare_freq_matrices.m#L67

**Comment by schoffelen** [comment]
OK, let's wait for the test functions to run through. If a new release can be created tomorrow, this PR does not have to be adjusted anymore, its draft status can be removed, and it can be merged.
@elshafeh note that this will be a news item in and of itself, in addition to a new-release item. Should we tweet twice about this, or should we move your tweet text to the respective new release news item?

**Comment by elshafeh** [comment]
> OK, let's wait for the test functions to run through. If a new release can be created tomorrow, this PR does not have to be adjusted anymore, its draft status can be removed, and it can be merged.
> @elshafeh note that this will be a news item in and of itself, in addition to a new-release item. Should we tweet twice about this, or should we move your tweet text to the respective new release news item?

sorry for not seeing this earlier. I suggest we announce this first and then tweet the new release mentioning this.

**Comment by robertoostenveld** [comment]
this is related to #327.

This one contains the news item that has to remain on the home page for some time. It explains the problem and consequences in more detail. The date (and link) is 27-november-2020.

**Pull request merged**
