### PR TITLE
add news item for release 20200826

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by Spaak** [comment]
@robertoostenveld @elshafeh See my edits. Specifically, note that I removed the detailed list of commits; I think this should be standard practice with news items. It's good to have them in the auto-generated PR template for reference, but if we decide to make a news item out of it, I think they should be removed. It clutters up the website and people can easily click through to GitHub using the provided link.

Also, I wanted to give credit to @octomike, but could not find his or her real name or Twitter handle. So instead I'm crediting the institute.

**Comment by robertoostenveld** [comment]
agreed with the summary. 

I think it would be  good to mention @octomike in the tweet anyway, but then without handle. For example like `... Thanks to octomike at @mpib_berlin!` Someone in control of the twitter mpib_berlin account might recognize the github handle and retweet it with the correct twitter name, thereby closing the loop. 

In the website part of the news item I suggest to write `...Thanks to the contributions made by [octomike](https://github.com/octomike) at ...`

**Comment by elshafeh** [comment]
> PS: I could merge this (thus triggering a Tweet), but am not sure whether to do it, since (a) the news is now somewhat old, and (b) we should stop the auto-tweeting of all commits before starting the new approach, I think.

Good point. I think we can adapt the tweets to highlight this as past releases. Something that would've been smoother following an announcement of our change in communications strategy (just saying). Something remains unclear: are tweets going to be sent automatically using the webhook? In other words, there's gonna be no use for twitter unless it's mirroring whatever is occurring in the GitHub? In other other words, we won't be able to retweet something that is relevant to us, reply to important mentions etc?

**Comment by Spaak** [comment]
> Something remains unclear: are tweets going to be sent automatically using the webhook? In other words, there's gonna be no use for twitter unless it's mirroring whatever is occurring in the GitHub? In other other words, we won't be able to retweet something that is relevant to us, reply to important mentions etc?

I think yes, news-item-related tweets are going to be sent automatically using the webhook. But I do think it would be important to also engage with Twitter in other ways, e.g. like retweeting and replying. Those cannot (and should not) be handled automatically.

**Comment by elshafeh** [comment]
> > Something remains unclear: are tweets going to be sent automatically using the webhook? In other words, there's gonna be no use for twitter unless it's mirroring whatever is occurring in the GitHub? In other other words, we won't be able to retweet something that is relevant to us, reply to important mentions etc?
> 
> I think yes, news-item-related tweets are going to be sent automatically using the webhook. But I do think it would be important to also engage with Twitter in other ways, e.g. like retweeting and replying. Those cannot (and should not) be handled automatically.

couldn't agree more!

**Comment by robertoostenveld** [comment]
since #282 refers to the most recent release, I have closed the two PRs for earlier releases.

**Pull request closed without merging**
