### PR TITLE
Fix several typos &  links in the tutorials & faq

### PR DESCRIPTION
**Pull request by complexbrains**
I made several corrections for the typos and links I encountered while going through the tutorials. Hope you find them useful.  
Thank you for the amazing tutorials and such an informative website!

### CODE REVIEW

**Review by schoffelen — APPROVED** [review]
OK, overall good! 2 small comments: clusterrandanalysis was once-upon-a-time the name of the function that did the non-parametric statistics + clustering, so I suggest a different change. Also, wrt neighbor vs. neighbour, if I recall well - in the past - it was discussed (and decided) to use US spelling rather then UK spelling. Yet, given the name of the function ft_prepare_neighbours, I'd say it make sense to stay with the British spelling here.

**Comment by schoffelen** [comment]
Thanks!

**Comment by complexbrains** [comment]
Dear @schoffelen Thank you very much for sharing these details. At some point I felt the clusterrandanalysis might not be a typo but was not having enough evidence regarding it, so made the correction thinking it is. 

Regarding neighbour vs neighbor usage, before making the change I also gone through some other texts to make sure what is the common usage across the webpage. Since I know such decisions are made on the conventions for projects but 
I realised some other texts were using the former. Therefore I aimed the consistency across. But I totally understand the usage now. 

Thank you for accepting all.

**Comment by schoffelen** [comment]
Sure, no problem. Please keep the fixes and other contributions coming!

**Comment by complexbrains** [comment]
Sure will do. Happy to help as much as I could.  Thank you.

**Pull request merged**
