### PR TITLE
Miscellaneous typo, style, and formatting fixes

### PR DESCRIPTION
**Pull request by apjanke**
Just some typo, grammar, style and formatting fixes. No substantive changes to content.

* Various grammar fixes
  * Replace comma splices with semicolons
* Capitalize "GitHub", "Git", "MATLAB", "MathWorks", "Windows" and "Bugzilla" consistently
* Spell out the names of Matlab toolboxes

* Add a "House prose guide" section in `README.md` reflecting this usage (which seems to be the current prevailing usage on the site)
* Note that the proportion of users with <5 year old Matlabs in that poll was 98%

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I should have done it in the correct order ... would have saved me from fixing the merge conflict.

Thanks once more!

**Comment by apjanke** [comment]
You're welcome! Thanks for taking my patches.

**Comment by robertoostenveld** [comment]
Could you send me an email, so that I have your address? I will then send you an invite to the FieldTrip slack workspace, since I think that some things might be faster discussed there, such as the testing framework.

**Comment by apjanke** [comment]
Done.

**Pull request merged**
