### PR TITLE
adding oslo folder with image

### PR DESCRIPTION
**Pull request by ualsbombe**
Would it be okay for us to have our own image folder, or do you prefer another solution, @robertoostenveld

### CODE REVIEW

**Comment by robertoostenveld** [comment]
your own image folder under assets makes sense. However, I propose that you keep the filenames simpler and don't include "oslo2019" in the name. That is already in the folder, so no reason to duplicate.

**Comment by ualsbombe** [comment]
Name has been simplified

**Comment by robertoostenveld** [comment]
Do you want me to merge this already (for testing purposes or so), or are you planning to add more?

**Comment by ualsbombe** [comment]
Please merge it now for testing purposes. Next time I add files, I will add all the ones that I need.

**Pull request merged**
