### PR TITLE
ENH shared preprocessing files structure & update respective tutorial…

### PR DESCRIPTION
**Pull request by aranas**
…s #196

### CODE REVIEW

**Comment by aranas** [comment]
@matsvanes 
Here we go, hope I didn't break anything

**Comment by schoffelen** [comment]
Shall I just merge and see what happens?

**Comment by aranas** [comment]
@matsvanes Could you take a quick look maybe, if you haven't already and before Jan-Mathijs merges? Just to be sure the changes I suggested would be compatible with your updates on the preprocessing/erp tutorials.

**Comment by matsvanes** [comment]
@aranas Looks good to me!

**Pull request merged**
