### PR TITLE
tutorial_cleaning

### PR DESCRIPTION
**Pull request by aranas**
Here is my draft of the 1st day tutorial. Although the frequency analysis is in there as well, since I thought we would have just one continuous file.

### CODE REVIEW

**Comment by aranas** [comment]
@dieloz @robertoostenveld

**Comment by robertoostenveld** [comment]
you made the changes in your master... that makes merging hard. next time better make a new branch (`git checkout -b whatever-name`) and make the changes in that one.

**Comment by dieloz** [comment]
yeah sorry... Surprisingly I cannot found how to pull a remote branch
git pull origin/madrid19 madrid19

**Comment by robertoostenveld** [comment]
I propose that both of you leave the git stuff to me for now.  Please add your markdown files to the shared dropbox, I will manage and merge them.

**Pull request closed without merging**
