### PR TITLE
once more round of cleanups of the madrid tutorials

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by aranas** [comment]
Hi,
I will be back on the grid from around 18h and can make some more changes if needed

**Comment by robertoostenveld** [comment]
ok. I just completed the review of the ERP tutorial and will also go through the other two. It would be good to go over all of them once more this evening.

**Comment by robertoostenveld** [comment]
@aranas and @dieloz please have a critical look at the cleaning tutorial and be prepared for questions: I already find it confusing, which means that the participants will probably not be able to follow it. In my review I did not make changes to the computations, only to the explanation. But I find  some parts of it not really FieldTrip-like.

**Comment by dieloz** [comment]
In an hour I'll take the train and I'll take over it

**Comment by robertoostenveld** [comment]
@aranas and @dieloz I have completed (what I plan to be my final) review of the tutorials and will merge them with the master to have them appear on the website. 

Please be gentle to the participants when they are doing the stats tutorial, since that is both conceptually and technically a challenging one (especially toward the end).

**Pull request merged**
