### PR TITLE
add news item for release 20201214

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by elshafeh** [comment]
nn

**Comment by schoffelen** [comment]
I think that this one is worth tweeting about. @elshafeh could you review and refine the tweet if necessary?

**Comment by elshafeh** [comment]
looks good :)

**Comment by robertoostenveld** [comment]
I removed the specific list of commits, that is in the template more as a reminder to us than for inclusion on the homepage. People that want to see commits can click on GitHub and see all relative to the last release that was announced.  

I also updated the previous version in `previous..current` to the one that was announced on twitter and the homepage.

**Pull request merged**
