### PR TITLE
add news item for release 20201009

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by elshafeh** [comment]
any chance we got the Twitter handle for (Janny)?

**Comment by robertoostenveld** [comment]
@jannystapel are you on twitter? If so, we can thank you explicitly for your contribution to the code fix in the nirs hackathon.

**Comment by jannystapel** [comment]
Yep, here is my twitter handle: @JannyStapel. Thanks for the explicit "thank you"!

**Comment by robertoostenveld** [comment]
is this ready to merge?

**Pull request merged**
